/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.psp.main;

import com.psp.doc.DocReader;

public class App {

	static String FILE_TYPE_DOC = "doc";
	static String FILE_TYPE_DOCX = "docx";

	public String getGreeting() {
		return "POI Demo";
	}

	public static void main(String[] args) {

		String fileType = args[0];
		if (fileType.equalsIgnoreCase(FILE_TYPE_DOC))
			DocReader.readDocFile(args[1]);
		else
			DocReader.readDocxFile(args[1]);
	}
}
