/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.psp.main;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.BeforeClass;
import org.junit.Test;

import com.psp.doc.DocReader;
import com.psp.main.App;

public class AppTest {

	private String DOC_FILE_NAME = "src/test/resources/sample_doc.doc";
	private String DOCX_FILE_NAME = "src/test/resources/sample_docx.docx";

	private static App classUnderTest;

	@BeforeClass
	public static void initialize() {
		classUnderTest = new App();
	}

	@Test
	public void testAppHasAGreeting() {
		assertNotNull("App should have a greeting", classUnderTest.getGreeting());
	}

	@Test
	public void testReadDocFile() {
		assertEquals(133, DocReader.readDocFile(DOC_FILE_NAME));
	}
	
	@Test
	public void testReadDocxFile() {
		assertEquals(90,  DocReader.readDocxFile(DOCX_FILE_NAME));
	}

}
